name: Publish development release
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm i --no-package-lock --no-audit --progress=false --prefer-offline
      - run: npm run build
      - run: zip obsidian-colored_tags_wrangler.zip main.js styles.css manifest.json README.md
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            obsidian-colored_tags_wrangler.zip
            main.js
            styles.css
            manifest.json